repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: .
    rev: f3820aadf099b2e7d79021bb4a6e6e8133e7b659
    hooks:
    -   id: pdoc

exclude: ^backend/docs/
